//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiScarpe.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DiScarpeDBEntities : DbContext
    {
        public DiScarpeDBEntities()
            : base("name=DiScarpeDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Carrinho> Carrinho { get; set; }
        public virtual DbSet<Categoria> Categoria { get; set; }
        public virtual DbSet<Cor> Cor { get; set; }
        public virtual DbSet<Estilo> Estilo { get; set; }
        public virtual DbSet<Favorito> Favorito { get; set; }
        public virtual DbSet<Marca> Marca { get; set; }
        public virtual DbSet<Produto> Produto { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Tamanho> Tamanho { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
    }
}
