//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiScarpe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Carrinho
    {
        public int IdCarrinho { get; set; }
        public int IdUsuario { get; set; }
        public int IdProduto { get; set; }
    }
}
